spring:
  application:
    name: eureka-discovery-service

server:
  port: 8080
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: https://apps-discovery-server.herokuapp.com/eureka